spring.application.name=todoapp
# Sunucumuzun çalışacağı port
server.port=${PORT:8080}
# Localhost üzerindeki 5432 portunda çalışan PostgreSQL'e ve todo_db veritabanına erişim adresi
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/todo_db}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

#Entity sınıflarına göre veritabanındaki tabloları otomatik günceller
spring.jpa.hibernate.ddl-auto=update
#Arka planda Hibernate tarafından çalıştırılan SQL sorgularını terminalde gösterir
spring.jpa.show-sql=true
# Terminalde görünen SQL sorgularını okunabilir olması için alt alta ve düzenli formatlar
spring.jpa.properties.hibernate.format_sql=true
# Hibernate'e PostgreSQL diyalekti/dili kullandığımızı belirten ayar
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:todoapp123456789012345678901234567890}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*}
spring.jackson.deserialization.fail-on-null-for-primitives=false
